import type {
  DemoResource,
  StandardsMappingExample,
  SubjectHub,
} from "@/types";

export const demoResources: DemoResource[] = [
  {
    id: "math-intervention-5",
    title: "Math Intervention Studio",
    subject: "Math",
    gradeBand: "Grade 5",
    standardsTag: "CCSS.MATH.CONTENT.5.NBT.B.7",
    updatedAt: "Updated 2 hours ago",
    format: "Intervention Pack",
    summary: "Decimal operations mini-lessons, guided practice, and small-group checks.",
    demoOnly: false,
    sellerName: "Avery Johnson",
    sellerHandle: "@teachwithavery",
    sellerId: "avery-johnson",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_AVERY",
    priceCents: 1200,
    isPurchasable: true,
  },
  {
    id: "ela-inference-4",
    title: "Inference Mini-Lessons Library",
    subject: "ELA",
    gradeBand: "Grade 4",
    standardsTag: "CCSS.ELA-LITERACY.RL.4.1",
    updatedAt: "Updated yesterday",
    format: "Workshop Slides",
    summary: "Short read-aloud prompts, modeling notes, and partner talk routines.",
    demoOnly: false,
    sellerName: "Monica Rivera",
    sellerHandle: "@ela.with.monica",
    sellerId: "monica-rivera",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_MONICA",
    priceCents: 900,
    isPurchasable: true,
  },
  {
    id: "science-ecosystems-6",
    title: "Science Lab Slides Collection",
    subject: "Science",
    gradeBand: "Grade 6",
    standardsTag: "MS-LS2-3",
    updatedAt: "Updated this week",
    format: "Lab Deck",
    summary: "Observation slides and claims-evidence-reasoning prompts for ecosystems.",
    demoOnly: false,
    sellerName: "Theo Barnes",
    sellerHandle: "@sciencewiththeo",
    sellerId: "theo-barnes",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_THEO",
    priceCents: 1500,
    isPurchasable: true,
  },
  {
    id: "social-studies-civics-5",
    title: "Civics Debate Toolkit",
    subject: "Social Studies",
    gradeBand: "Grades 3-5",
    standardsTag: "D2.Civ.4.3-5",
    updatedAt: "New in demo mode",
    format: "Discussion Toolkit",
    summary: "Primary sources, debate sentence stems, and reflection pages.",
    demoOnly: true,
    sellerName: "Priya Ellis",
    sellerHandle: "@historywithpriya",
    sellerId: "priya-ellis",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_PRIYA",
    priceCents: 1100,
    isPurchasable: true,
  },
  {
    id: "math-fractions-4",
    title: "Fraction Strategy Studio",
    subject: "Math",
    gradeBand: "Grade 4",
    standardsTag: "CCSS.MATH.CONTENT.4.NF.A.1",
    updatedAt: "Demo preview",
    format: "Practice Center",
    summary: "Visual fraction models, station cards, and independent practice sheets.",
    demoOnly: true,
    sellerName: "Avery Johnson",
    sellerHandle: "@teachwithavery",
    sellerId: "avery-johnson",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_AVERY",
    priceCents: 800,
    isPurchasable: true,
  },
  {
    id: "math-algebra-toolkit",
    title: "Algebra Warm-Up Toolkit",
    subject: "Math",
    gradeBand: "Algebra 1",
    standardsTag: "CCSS.MATH.CONTENT.HSA.CED.A.1",
    updatedAt: "Uploaded by a teacher this week",
    format: "Warm-Up Pack",
    summary: "Bell ringers, mini whiteboard prompts, and scaffolded checks for algebraic thinking.",
    demoOnly: false,
    sellerName: "Nina Brooks",
    sellerHandle: "@numbers.with.nina",
    sellerId: "nina-brooks",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_AVERY",
    priceCents: 1000,
    isPurchasable: true,
  },
  {
    id: "math-multiplication-fluency-3",
    title: "Multiplication Fluency Sprint",
    subject: "Math",
    gradeBand: "Grade 3",
    standardsTag: "CCSS.MATH.CONTENT.3.OA.C.7",
    updatedAt: "Updated this week",
    format: "Fact Fluency Pack",
    summary: "Timed practice pages, strategy mats, and quick checks for multiplication fluency.",
    demoOnly: false,
    sellerName: "Avery Johnson",
    sellerHandle: "@teachwithavery",
    sellerId: "avery-johnson",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_AVERY",
    priceCents: 700,
    isPurchasable: true,
  },
  {
    id: "math-geometry-centers-5",
    title: "Geometry Centers Toolkit",
    subject: "Math",
    gradeBand: "Grade 5",
    standardsTag: "CCSS.MATH.CONTENT.5.G.B.4",
    updatedAt: "Fresh teacher upload",
    format: "Centers Pack",
    summary: "Hands-on geometry task cards, vocabulary support, and station recording sheets.",
    demoOnly: true,
    sellerName: "Nina Brooks",
    sellerHandle: "@numbers.with.nina",
    sellerId: "nina-brooks",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_AVERY",
    priceCents: 1100,
    isPurchasable: true,
  },
  {
    id: "ela-writing-conference-kit",
    title: "Writing Conference Toolkit",
    subject: "ELA",
    gradeBand: "Grade 5",
    standardsTag: "CCSS.ELA-LITERACY.W.5.4",
    updatedAt: "Teacher upload",
    format: "Conference Toolkit",
    summary: "Conferring prompts, revision trackers, and student reflection sheets for writing workshop.",
    demoOnly: false,
    sellerName: "Monica Rivera",
    sellerHandle: "@ela.with.monica",
    sellerId: "monica-rivera",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_MONICA",
    priceCents: 1300,
    isPurchasable: true,
  },
  {
    id: "ela-close-reading-routines",
    title: "Close Reading Routines Set",
    subject: "ELA",
    gradeBand: "Grade 6",
    standardsTag: "CCSS.ELA-LITERACY.RI.6.1",
    updatedAt: "Fresh teacher listing",
    format: "Routine Pack",
    summary: "Annotation templates, evidence stems, and repeatable close-reading structures.",
    demoOnly: true,
    sellerName: "Leah Patel",
    sellerHandle: "@readwithleah",
    sellerId: "leah-patel",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_MONICA",
    priceCents: 950,
    isPurchasable: true,
  },
  {
    id: "ela-vocabulary-routines-3",
    title: "Vocabulary Routine Builder",
    subject: "ELA",
    gradeBand: "Grade 3",
    standardsTag: "CCSS.ELA-LITERACY.L.3.4",
    updatedAt: "Updated yesterday",
    format: "Routine Pack",
    summary: "Word-study mini lessons, context clue tasks, and partner talk cards for vocabulary practice.",
    demoOnly: false,
    sellerName: "Leah Patel",
    sellerHandle: "@readwithleah",
    sellerId: "leah-patel",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_MONICA",
    priceCents: 850,
    isPurchasable: true,
  },
  {
    id: "ela-poetry-response-5",
    title: "Poetry Response Mini Unit",
    subject: "ELA",
    gradeBand: "Grade 5",
    standardsTag: "CCSS.ELA-LITERACY.RL.5.5",
    updatedAt: "New in demo mode",
    format: "Mini Unit",
    summary: "Poem response pages, annotation prompts, and writing stems for poetry discussions.",
    demoOnly: true,
    sellerName: "Monica Rivera",
    sellerHandle: "@ela.with.monica",
    sellerId: "monica-rivera",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_MONICA",
    priceCents: 1200,
    isPurchasable: true,
  },
  {
    id: "science-claim-evidence-routines",
    title: "Claim Evidence Reasoning Routines",
    subject: "Science",
    gradeBand: "Grade 7",
    standardsTag: "MS-ETS1-3",
    updatedAt: "Teacher upload",
    format: "CER Toolkit",
    summary: "Sentence stems, notebook organizers, and lab debrief structures for CER writing.",
    demoOnly: false,
    sellerName: "Theo Barnes",
    sellerHandle: "@sciencewiththeo",
    sellerId: "theo-barnes",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_THEO",
    priceCents: 1400,
    isPurchasable: true,
  },
  {
    id: "science-stem-lab-starters",
    title: "STEM Lab Starter Bundle",
    subject: "Science",
    gradeBand: "High School",
    standardsTag: "HS-ETS1-2",
    updatedAt: "New seller resource",
    format: "Starter Bundle",
    summary: "Launch slides, planning sheets, and reflection prompts for hands-on STEM tasks.",
    demoOnly: true,
    sellerName: "Camila Torres",
    sellerHandle: "@stemwithcamila",
    sellerId: "camila-torres",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_THEO",
    priceCents: 1600,
    isPurchasable: true,
  },
  {
    id: "science-weather-patterns-4",
    title: "Weather Patterns Inquiry Pack",
    subject: "Science",
    gradeBand: "Grade 4",
    standardsTag: "4-ESS2-1",
    updatedAt: "Teacher upload",
    format: "Inquiry Pack",
    summary: "Observation charts, weather data pages, and claim-writing prompts for pattern spotting.",
    demoOnly: false,
    sellerName: "Theo Barnes",
    sellerHandle: "@sciencewiththeo",
    sellerId: "theo-barnes",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_THEO",
    priceCents: 1150,
    isPurchasable: true,
  },
  {
    id: "science-physical-changes-3",
    title: "Physical Changes Lab Set",
    subject: "Science",
    gradeBand: "Grade 3",
    standardsTag: "3-PS2-3",
    updatedAt: "Recently uploaded",
    format: "Lab Set",
    summary: "Hands-on lab pages, prediction sheets, and observation prompts for physical change lessons.",
    demoOnly: true,
    sellerName: "Camila Torres",
    sellerHandle: "@stemwithcamila",
    sellerId: "camila-torres",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_THEO",
    priceCents: 1250,
    isPurchasable: true,
  },
  {
    id: "social-studies-primary-source-kit",
    title: "Primary Source Analysis Kit",
    subject: "Social Studies",
    gradeBand: "Grades 3-5",
    standardsTag: "D2.His.1.3-5",
    updatedAt: "Teacher upload",
    format: "Source Analysis Pack",
    summary: "Observation guides, sourcing questions, and evidence trackers for primary source study.",
    demoOnly: false,
    sellerName: "Priya Ellis",
    sellerHandle: "@historywithpriya",
    sellerId: "priya-ellis",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_PRIYA",
    priceCents: 1250,
    isPurchasable: true,
  },
  {
    id: "social-studies-geography-studio",
    title: "Geography Inquiry Studio",
    subject: "Social Studies",
    gradeBand: "Grades K-2",
    standardsTag: "D2.Geo.4.K-2",
    updatedAt: "Recently uploaded",
    format: "Inquiry Pack",
    summary: "Map questions, region comparisons, and inquiry boards for geography lessons.",
    demoOnly: true,
    sellerName: "Owen Carter",
    sellerHandle: "@mapswithowen",
    sellerId: "owen-carter",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_PRIYA",
    priceCents: 1050,
    isPurchasable: true,
  },
  {
    id: "social-studies-community-helpers-k2",
    title: "Community Helpers Inquiry Pack",
    subject: "Social Studies",
    gradeBand: "Grades K-2",
    standardsTag: "D2.Civ.6.K-2",
    updatedAt: "Updated this week",
    format: "Inquiry Pack",
    summary: "Sorting mats, discussion cards, and neighborhood helper activities for early elementary classrooms.",
    demoOnly: false,
    sellerName: "Owen Carter",
    sellerHandle: "@mapswithowen",
    sellerId: "owen-carter",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_PRIYA",
    priceCents: 900,
    isPurchasable: true,
  },
  {
    id: "social-studies-government-4",
    title: "Branches of Government Mini Unit",
    subject: "Social Studies",
    gradeBand: "Grade 4",
    standardsTag: "D2.Civ.12.3-5",
    updatedAt: "New seller resource",
    format: "Mini Unit",
    summary: "Anchor charts, reading pages, and sorting tasks for understanding local and national government.",
    demoOnly: true,
    sellerName: "Priya Ellis",
    sellerHandle: "@historywithpriya",
    sellerId: "priya-ellis",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_PRIYA",
    priceCents: 1350,
    isPurchasable: true,
  },
];

export const subjectHubs: SubjectHub[] = [
  {
    name: "Math",
    description: "Intervention sets, spiral review, and number talks adaptable across K-12 classrooms.",
    resourceCount: "148 resources",
    spotlight: "Intervention units and number sense routines for any grade level",
    gradeBand: "K-12",
    colorClass: "bg-blue-50 text-blue-700",
  },
  {
    name: "ELA",
    description: "Workshop units, close reads, and vocabulary packs adaptable across K-12 literacy blocks.",
    resourceCount: "203 resources",
    spotlight: "Reading workshops and writing conferences for all grade bands",
    gradeBand: "K-12",
    colorClass: "bg-amber-50 text-amber-700",
  },
  {
    name: "Science",
    description: "Labs, CER routines, and standards-linked observation templates for K-12 science instruction.",
    resourceCount: "92 resources",
    spotlight: "Labs, CER writing, and inquiry prompts across K-12 science",
    gradeBand: "K-12",
    colorClass: "bg-emerald-50 text-emerald-700",
  },
  {
    name: "Social Studies",
    description: "Primary source sets, map work, and discussion prompts adaptable across K-12 social studies.",
    resourceCount: "76 resources",
    spotlight: "Primary sources and civic discussion kits for any grade level",
    gradeBand: "K-12",
    colorClass: "bg-violet-50 text-violet-700",
  },
];

export const standardsMappingExamples: StandardsMappingExample[] = [
  {
    id: "math-decimals",
    title: "Decimal Operations Exit Ticket",
    subject: "Math",
    gradeBand: "Grade 5",
    excerpt:
      "Students solve decimal addition and subtraction problems using visual models and explain each step in writing.",
    suggestedStandard: "CCSS.MATH.CONTENT.5.NBT.B.7",
    rationale:
      "The lesson focuses on adding and subtracting decimals to hundredths using concrete models and written explanation.",
  },
  {
    id: "ela-theme",
    title: "Theme and Evidence Quick Check",
    subject: "ELA",
    gradeBand: "Grade 4",
    excerpt:
      "Students identify a theme in a short story and cite two details that support their thinking during partner discussion.",
    suggestedStandard: "CCSS.ELA-LITERACY.RL.4.2",
    rationale:
      "The task asks students to determine theme and support it with text details from literature.",
  },
  {
    id: "science-ecosystems",
    title: "Ecosystem Interaction Notebook",
    subject: "Science",
    gradeBand: "Grade 6",
    excerpt:
      "Students analyze how changes in a local pond ecosystem affect organisms and build a written explanation from observations.",
    suggestedStandard: "MS-LS2-4",
    rationale:
      "The notebook asks students to explain ecosystem changes and their impact on populations based on evidence.",
  },
];
