import type {
  DemoResource,
  StandardsMappingExample,
  SubjectHub,
} from "@/types";
import { launchProductAssetSeeds } from "@/lib/lessonforge/launch-product-assets";

const demoPreviewResources: DemoResource[] = [
  {
    id: "demo-civics-discussion-kit",
    title: "Civics Discussion Kit",
    subject: "Social Studies",
    gradeBand: "Grades 3-5",
    standardsTag: "D2.Civ.4.3-5",
    tags: ["demo preview", "civics", "discussion prompts"],
    updatedAt: "Preview catalog only",
    format: "Discussion Toolkit",
    summary: "A preview-only civics discussion sample used to show the separate public preview path without affecting the live marketplace catalog.",
    shortDescription:
      "This preview-only listing stays outside the live marketplace so we can keep a safe public preview surface for internal demos.",
    fullDescription:
      "This listing exists only for the separate preview surface and is intentionally not part of the live marketplace catalog. Buyers do not see it in the main marketplace, and it does not participate in the protected seeded download flow.",
    demoOnly: true,
    resourceType: "Discussion Toolkit",
    licenseType: "Single classroom",
    fileTypes: ["PDF"],
    includedItems: [
      "Preview-only sample card",
      "Teacher discussion prompts",
      "Seller-facing preview notes",
      "Non-purchasable demo surface",
    ],
    previewIncluded: true,
    thumbnailIncluded: true,
    rightsConfirmed: true,
    assetVersionNumber: 1,
    freshnessScore: 4,
    sellerName: "LessonForge Marketplace",
    sellerHandle: "Platform starter resource",
    sellerId: "priya-ellis",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_PRIYA",
    priceCents: 700,
    isPurchasable: false,
    productStatus: "Published",
    createdPath: "Manual upload",
  },
  {
    id: "demo-science-slide-preview",
    title: "Weather Discussion Slides Preview",
    subject: "Science",
    gradeBand: "Grades 3-5",
    standardsTag: "3-ESS2-1",
    tags: ["demo preview", "science", "slide sample"],
    updatedAt: "Preview catalog only",
    format: "Slide Deck",
    summary: "A non-purchasable science preview listing that keeps the dedicated preview routes working without crossing into the live store catalog.",
    shortDescription:
      "This listing is reserved for the separate preview flow and does not appear in the launch-ready marketplace catalog.",
    fullDescription:
      "This slide preview remains useful for internal testing of the preview-only experience, while the live marketplace now uses real product files and real preview pages pulled from those files.",
    demoOnly: true,
    resourceType: "Slide Deck",
    licenseType: "Single classroom",
    fileTypes: ["PDF"],
    includedItems: [
      "Preview-only slide sample",
      "Teacher-facing discussion prompt notes",
      "Internal preview testing coverage",
      "No live checkout or protected delivery mapping",
    ],
    previewIncluded: true,
    thumbnailIncluded: true,
    rightsConfirmed: true,
    assetVersionNumber: 1,
    freshnessScore: 4,
    sellerName: "LessonForge Marketplace",
    sellerHandle: "Platform starter resource",
    sellerId: "theo-barnes",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_THEO",
    priceCents: 900,
    isPurchasable: false,
    productStatus: "Published",
    createdPath: "Manual upload",
  },
  {
    id: "demo-writing-preview-pack",
    title: "Narrative Prompt Preview Pack",
    subject: "Writing",
    gradeBand: "Grades 3-5",
    standardsTag: "CCSS.ELA-LITERACY.W.4.3",
    tags: ["demo preview", "writing", "prompt pack"],
    updatedAt: "Preview catalog only",
    format: "Prompt Pack",
    summary: "A preview-only writing sample preserved for the separate public preview surface.",
    shortDescription:
      "This listing keeps a non-live preview route available without putting placeholder content into the real marketplace.",
    fullDescription:
      "The live marketplace catalog now uses real files, real preview pages, and protected delivery. This preview-only writing sample is kept only so the dedicated preview surface still has a safe non-live listing to show.",
    demoOnly: true,
    resourceType: "Prompt Pack",
    licenseType: "Single classroom",
    fileTypes: ["PDF"],
    includedItems: [
      "Preview-only prompt sample",
      "Internal demo coverage",
      "Teacher-facing note card",
      "No live product file mapping",
    ],
    previewIncluded: true,
    thumbnailIncluded: true,
    rightsConfirmed: true,
    assetVersionNumber: 1,
    freshnessScore: 4,
    sellerName: "LessonForge Marketplace",
    sellerHandle: "Platform starter resource",
    sellerId: "monica-rivera",
    sellerStripeAccountEnvKey: "STRIPE_CONNECTED_ACCOUNT_MONICA",
    priceCents: 650,
    isPurchasable: false,
    productStatus: "Published",
    createdPath: "Manual upload",
  },
];

const seededLaunchResources: DemoResource[] = launchProductAssetSeeds.map((seed) => ({
  id: seed.id,
  slug: seed.slug,
  title: seed.title,
  subject: seed.subject,
  gradeBand: seed.gradeBand,
  standardsTag: seed.standardsTag,
  tags: seed.tags,
  pageCount: seed.pageCount,
  updatedAt: seed.updatedAt,
  format: seed.format,
  summary: seed.summary,
  shortDescription: seed.shortDescription,
  fullDescription: seed.fullDescription,
  demoOnly: false,
  resourceType: seed.resourceType,
  licenseType: seed.licenseType,
  fileTypes: seed.fileTypes,
  includedItems: seed.includedItems,
  previewLabels: seed.previewLabels,
  previewPages: seed.previewPages,
  thumbnailUrl: seed.thumbnailUrl,
  previewAssetUrls: seed.previewAssetUrls,
  originalAssetUrl: seed.originalAssetUrl,
  assetVersionNumber: seed.assetVersionNumber,
  previewIncluded: seed.previewIncluded,
  thumbnailIncluded: seed.thumbnailIncluded,
  rightsConfirmed: seed.rightsConfirmed,
  freshnessScore: seed.freshnessScore,
  sellerName: seed.sellerName,
  sellerHandle: seed.sellerHandle,
  sellerId: seed.sellerId,
  sellerStripeAccountEnvKey: seed.sellerStripeAccountEnvKey,
  priceCents: seed.priceCents,
  isPurchasable: seed.isPurchasable,
  productStatus: seed.productStatus,
  createdPath: seed.createdPath,
}));

export const demoResources: DemoResource[] = [
  ...seededLaunchResources,
  ...demoPreviewResources,
];

export const subjectHubs: SubjectHub[] = [
  {
    name: "Math",
    description: "Spiral review, number sense, fractions, geometry, and intervention resources for K-5 classrooms.",
    resourceCount: "8 live products",
    spotlight: "Daily review, intervention, and printable math practice",
    gradeBand: "K-5",
    colorClass: "bg-blue-50 text-blue-700",
  },
  {
    name: "Reading",
    description: "Passages, main idea practice, context clues, and reading test prep for upper elementary readers.",
    resourceCount: "4 live products",
    spotlight: "Readable passages and text evidence practice",
    gradeBand: "Grades 3-5",
    colorClass: "bg-rose-50 text-rose-700",
  },
  {
    name: "Writing",
    description: "Paragraph, opinion, and narrative writing resources with teacher support and printable student pages.",
    resourceCount: "3 live products",
    spotlight: "Writing workshop tools and structured drafting practice",
    gradeBand: "Grades 3-5",
    colorClass: "bg-amber-50 text-amber-700",
  },
  {
    name: "Science",
    description: "Life cycles, weather, and ecosystems resources with observation pages and written response support.",
    resourceCount: "3 live products",
    spotlight: "Simple investigations and notebook-ready science pages",
    gradeBand: "Grades 2-5",
    colorClass: "bg-emerald-50 text-emerald-700",
  },
  {
    name: "Social Studies",
    description: "Communities, map skills, and government resources designed for clear elementary social studies instruction.",
    resourceCount: "3 live products",
    spotlight: "Civics, geography, and community-building pages",
    gradeBand: "Grades 2-5",
    colorClass: "bg-violet-50 text-violet-700",
  },
  {
    name: "Classroom Tools",
    description: "Classroom management, morning work, intervention, and seasonal resources that support daily routines.",
    resourceCount: "7 live products",
    spotlight: "Teacher-ready routines, reflection pages, and seasonal supports",
    gradeBand: "K-5",
    colorClass: "bg-slate-100 text-slate-700",
  },
];

export const standardsMappingExamples: StandardsMappingExample[] = [
  {
    id: "math-decimals",
    title: "5th Grade Decimal Operations",
    subject: "Math",
    gradeBand: "Grade 5",
    excerpt:
      "Students solve decimal addition, subtraction, and multiplication problems while explaining how place value supports each step.",
    suggestedStandard: "CCSS.MATH.CONTENT.5.NBT.B.7",
    rationale:
      "The resource asks students to compute with decimals to hundredths and explain their strategy with place value language.",
  },
  {
    id: "reading-main-idea",
    title: "4th Grade Main Idea and Details",
    subject: "Reading",
    gradeBand: "Grade 4",
    excerpt:
      "Students identify the main idea of a short informational text and choose details that best support it.",
    suggestedStandard: "CCSS.ELA-LITERACY.RI.4.2",
    rationale:
      "The reading task focuses on determining the main idea and explaining how details support that central point.",
  },
  {
    id: "science-ecosystems",
    title: "5th Grade Ecosystems",
    subject: "Science",
    gradeBand: "Grade 5",
    excerpt:
      "Students build a simple food chain, explain how a population change affects the system, and support a claim with evidence.",
    suggestedStandard: "5-LS2-1",
    rationale:
      "The pages ask students to model movement of matter and explain how changes in one part of an ecosystem affect the whole.",
  },
];
